export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANY = 'GET_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAIL = 'GET_COMPANIES_FAIL';
export const UPVOTE_COMPANY = 'UPVOTE_COMPANY';
export const DOWNVOTE_COMPANY = 'DOWNVOTE_COMPANY'
export const CREATE_COMPANY = 'CREATE_COMPANY'

export const COMPANIES_URL = '/companies';
